SCENARIO: "Scenario"
DOCUMENTATION: "Documentation:"
VARIABLE_SETTINGS: "Variable Settings"
GIVEN: "Given "
WHEN: "When "
THEN: "Then "
AND_STEP: "And "

SUCHTHAT: "such that:"
INITCOND: "the system is in its initial state"

ISA: "is a " | "is an "
ISTHE: "is the "
WITHRANGE: "with range "
RESOLUTION: "resolution "
AND_INITIAL_VALUE: "and initial value "

ARRAYOF: "array of "
UNIQUE: "unique "

CONTAINS_ALL_POSSIBLE_ELEMENTS: "contains all possible elements"
CONTAINS_ONLY: "contains only "
CONTAINS: "contains "
DOES_NOT_CONTAIN: "does not contain "

IS_EMPTY: "is empty"
IS_NOT_EMPTY: "is not empty"

IS_A_STRUCTURE_WITH_ATTRIBUTES: "is a structure with attributes "

HAS_ATTRIBUTES_SUCH_THAT: "has attributes such that:"

ELEMENTS_WHERE_EACH_ELEMENT: "elements where each element "

BOOLEAN_TYPE: "boolean"
STRING_TYPE: "string"
INTEGER_TYPE: "integer"
DECIMAL_TYPE: "float"

BOOLEAN_TYPE_PL: "booleans"
STRING_TYPE_PL: "strings"
INTEGER_TYPE_PL: "integers"
DECIMAL_TYPE_PL: "floats"

HAS: "has"
IS: "is"

IN: "in " | "is in "
NOT_IN: "not in " | "is not in "

LENGTH: "length "
SUBSET_OF: "subset of "

EQUAL_TO: "equal to "
NOT_EQUAL_TO: "not equal to "
GREATER_THAN: "greater than "
LOWER_THAN: "lower than "
GREATER_OR_EQUAL_THAN: "greater or equal than "
LOWER_OR_EQUAL_THAN: "lower or equal than "

AT_LEAST: "at least "
AT_MOST: "at most "
EXACTLY: "exactly "
ALL: "all "
BETWEEN: "between "
AND: "and "

BOOL_LIT: "true" | "false"

STORED: "stored "
CONJOP: "AND" | "OR"

QUOTE: "\""
COMMA: ","
